name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish Chrome Web Extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - run: yarn --immutable
      - run: yarn format:check
      - run: yarn lint

      - name: Get version number
        id: semver
        run: ./scripts/semver.sh

      - name: Update theme version number
        if: ${{ steps.semver.outputs.VERSION != '' }}
        run: sed -i 's/0.0.0/${{ steps.semver.outputs.VERSION }}/g' manifest.json

      - run: yarn prod

      - run: zip -r release.zip *
        working-directory: dist

      - run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload & release
        uses: mnao305/chrome-extension-upload@v4.0.0
        with:
          file-path: dist/release.zip
          extension-id: pjegkjcbjfoldlpcbjniaceihlkjdkeg
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
